url: http://phpne.org.uk
google_analytics_id: UA-46863902-1
google_api_key: AIzaSyDnkQrvUL1pFX9pEYnptILZ4PfWoqegMKQ
markdown: kramdown
paginate: 10
timezone: Europe/London
future: true

gems:
  - jekyll-paginate

exclude:
  - node_modules
  - CNAME
  - LICENSE
  - README.md
  - Vagrantfile
  - gulpfile.js
  - package-lock.json
  - package.json

future: true

collections:
  sponsors:
    output: false
